### ISSUE TITLE
Applying this back into NetworkX

### ISSUE THREAD

**Issue by BradKML** [iandreafc/distinctiveness-centrality#3]
This is an idea to see if it can be compared with other Centrality algorithms used in Networkx
- https://github.com/SelinHulagu/Analysis-of-Network-Centrality-Measures-in-Python/blob/main/jupyter_codes_comments.ipynb
- https://github.com/nlztrk/centrality_correlations/blob/main/analysis.ipynb

**Comment by iandreafc** [comment]
Thanks Brandon this is certainly interesting. From our preliminary tests (also in the paper https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0233276), correlations will be high for some network structures and lower for others (probably more sparse networks). Also changing the Alpha parameter will make a big difference.

By the way, I tried to integrate the metric into Networkx and opened a thread with code about 1 year ago, but still this has to be considered. Happy if you want to contribute to that.

Thanks again!
